services:
  - type: worker
    name: smart-quiz-telegram-bot
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run prisma:generate
    startCommand: npm run start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
